# Generated by Django 3.2.9 on 2021-12-09 23:36

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
