# Generated by Django 3.2.9 on 2021-12-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
