# Generated by Django 3.2.9 on 2021-12-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_remove_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='media/registro_imagenes')),
            ],
        ),
    ]
