# Generated by Django 3.2.9 on 2021-12-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='Imagen', upload_to='media/registro_imagenes'),
            preserve_default=False,
        ),
    ]
