# Generated by Django 3.2.9 on 2021-12-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20211209_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
