# Generated by Django 3.2.9 on 2021-12-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='media/profile'),
        ),
    ]
